services:
  - type: web
    name: ninjabase-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT app:app --timeout 120
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8947717190:AAHzv4jGRFxpZEYYq-3PA_iwEerouQj7ABY
      - key: PYTHON_VERSION
        value: 3.14.3
